version: '3.9'
services:
  node:
    container_name: pepalBot_node
    image: node:16-alpine
    restart: unless-stopped
    working_dir: /app
    command: 'npm run start:$ENVIRONMENT'
    volumes:
      - .:/app
    links:
      - db

networks:
  default:
    external:
      name: dbNetwork
